### ISSUE TITLE
compile problem with lzma-4.999.5alpha

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hexxellor/fusecompress#31]
```
Hi

I download your fusecompress 0.9.x source from google code and have problem
compile it. "make release" complains:

compress_lzma.o: In function `lzmaCompress':
/usr/src/fusecompress-read-only/compress_lzma.c:53: undefined reference to
`lzma_easy_encoder_single'
compress_lzma.o: In function `lzmaOpen':
/usr/src/fusecompress-read-only/compress_lzma.c:220: undefined reference to
`lzma_easy_encoder_single'
collect2: ld returned 1 exit status
make: *** [fusecompress] Error 1

Could you take a look?

Thanks

```

Original issue reported on code.google.com by `nguyenth...@gmail.com` on 9 Nov 2008 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Looks like the LZMA API changed. It should work if you replace references to
"lzma_easy_encoder_single" with "lzma_easy_encoder".
```

Original comment by `ulrich.h...@gmail.com` on 11 Nov 2008 at 2:23
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
fixed to compile with both 4.999.3 and 4.999.5 (r78)

Please be aware that liblzma 4.999.3 and 4.999.5 are not compatible, and data 
written
with one cannot be read with the other.
```

Original comment by `ulrich.h...@gmail.com` on 11 Nov 2008 at 2:52
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks. 

It would be nice to allow lzma to be optional at the compilation level (like 
"make
releaseNoLZMA"). I never use alpha software so downloading/installing lzma on my
system is a bit unsettling for me. My kubuntu distro doesn't come with it.
```

Original comment by `nguyenth...@gmail.com` on 11 Nov 2008 at 10:50
